### ISSUE TITLE
Error with clean_IGRA_V2

### ISSUE THREAD

**Issue by franciscoleoncrz** [kcf-jackson/cleanIGRA#1]
> mydata <- clean_IGRA_v2(filepath)
Parsing the file...Done! 
Error in `dplyr::bind_cols()`:
! Can't recycle `..1` (size 260) to match `..2` (size 389).
Run `rlang::last_error()` to see where the error occurred.
Warning message:
One or more parsing issues, see `problems()` for details

**Comment by kcf-jackson** [comment]
Thanks for reporting the issue.

I am able to reproduce the error. The error is caused by a breaking change in the `readr` package. Under `?read_fwf`, it says

> Second edition changes
Comments are no longer looked for anywhere in the file. They are now only ignored at the start of a line.

This caused the mismatch of numbers of rows between the header and the data and hence the error. I have fixed it and pushed an update to repo. Reinstall the package and everything should work again.

**Comment by franciscoleoncrz** [comment]
Hello, kcf-jackson

> Thanks for reporting the issue.
> 
> I am able to reproduce the error. The error is caused by a breaking change in the `readr` package. Under `?read_fwf`, it says
> 
> Second edition changes
> Comments are no longer looked for anywhere in the file. They are now only ignored at the start of a line.
> 
> This caused the mismatch of numbers of rows between the header and the data and hence the error. I have fixed it and pushed an update to repo. Reinstall the package and everything should work again.

Thank you so much for your quick reply, 
The issue has been solve. 

Cheers!
